<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	
  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrbanNative.Application\UrbanNative.Application.csproj" />
    <ProjectReference Include="..\UrbanNative.Shared\UrbanNative.Shared.csproj" />
  </ItemGroup>

</Project>
